export const USER_REGISTERATION_REQUEST = "USER_REGISTERATION_REQUEST";
export const USER_REGISTERATION_SUCCESS = "USER_REGISTERATION_SUCCESS";
export const USER_REGISTERATION_FAIL = "USER_REGISTERATION_FAIL";
export const USER_REGISTERATION_RESET = "USER_REGISTERATION_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

export const USER_LOGOUT = "USER_LOGOUT";
