export const GET_USER_TASKS_REQUEST = "GET_USER_TASKS_REQUEST";
export const GET_USER_TASKS_SUCCESS = "GET_USER_TASKS_SUCCESS";
export const GET_USER_TASKS_FAIL = "GET_USER_TASKS_FAIL";
export const GET_USER_TASKS_RESET = "GET_USER_TASKS_RESET";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";
export const ADD_TASK_RESET = "ADD_TASK_RESET";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";

export const GET_TASK_BY_ID_REQUEST = "GET_TASK_BY_ID_REQUEST";
export const GET_TASK_BY_ID_SUCCESS = "GET_TASK_BY_ID_SUCCESS";
export const GET_TASK_BY_ID_FAIL = "GET_TASK_BY_ID_FAIL";
export const GET_TASK_BY_ID_RESET = "GET_TASK_BY_ID_RESET";

export const GET_TASK_BY_RANK_REQUEST = "GET_TASK_BY_RANK_REQUEST";
export const GET_TASK_BY_RANK_SUCCESS = "GET_TASK_BY_RANK_SUCCESS";
export const GET_TASK_BY_RANK_FAIL = "GET_TASK_BY_RANK_FAIL";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET";
