export const GET_USER_TASKS_REQUEST = "GET_USER_TASKS_REQUEST";
export const GET_USER_TASKS_SUCCESS = "GET_USER_TASKS_SUCCESS";
export const GET_USER_TASKS_FAIL = "GET_USER_TASKS_FAIL";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
